### PR TITLE
PR for Homepage, Categories and Rules page.

### PR DESCRIPTION
**Pull request by manojasarsa**
This PR includes:
- Home page with categories
- Rules page

### CODE REVIEW

**Comment by manojasarsa** [comment]
image


image

**Review by adidoshi — COMMENTED** [review]
Code looks good👍... one suggestion, if the text color of rules list can be changed.

**Review by someshtiwarii — APPROVED** [review]
good to go

**Review by tanveertkd — APPROVED** [review]
Could you try playing around with the colors a bit? A better contrast ratio will help this stand out much better. Otherwise, it looks good to me!

**Comment by manojasarsa** [comment]
> Could you try playing around with the colors a bit? A better contrast ratio will help this stand out much better. Otherwise, it looks good to me!

Sure, Tanveer! I'll will have a look on this again.

**Comment by manojasarsa** [comment]
> Code looks good👍... one suggestion, if the text color of rules list can be changed.

Sure, Can you suggest any color related to the theme for rules text that comes in your mind ?

**Pull request merged**
